name: "Lint"
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./motivator
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm ci --dev
    - name: Typescript check
      run: npx tsc
    - name: Lint
      run: npm run lint
    - name: Format check
      run: npm run format:check

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        milliseconds: 1000
